apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgCXRpPG3Z1UVJ9QsQcyn0PmFX6rCdkmAE1hc+XXETKCmIiPDICu8hwcHLPdUstBsx8qEZY/Zr2JK9CEyjoUnlUr1oq0BXgBhkRlHE2NQih5lhTFgNZu1WGJIPgKMgbFIXNIqpFBqKiZFO4cguv+3YP0rOZoA6LfGqUKLR71FULC9X+sDu2GICoeKYSgxSio13yMenLx5fi9ctCBQ80WyaB7ZIrpdVbSq6wHqxLMQn4+VPB8aiL0zy8apMPM8fbPR/HHgrGg2ETMUxq4dsvjqnyIvqS9yxVFGJoEjjnLIEjj2QPsI055WdkzWgFBCaELMyD9xVbX6qwcOpZ809dxLigbJX26UVp8vI+WN6PFprBPLNFFLJyL+U8VCtXCMVSdnS4UT+rOpW4LlvtbgHsjlyAF+NDE892bcwxnt+EBRWRugH6o3V+3qmVVaPRzC2dx+Fwv7z5qthd0VLeOLQJ/JK8XFAi51hKnS3fhiQ8fknVmRnYeaAyQ7Zr01xEWa16uePNwZ5b95OOoQh0dnX1e2axFpQwr/8rtcdVqdLdv0tEXQ1gH0TaAszfHtGVzDK26AjCfX22OEdFavlD73tV+r9mYnhdhfpuG4K/lWISe7Wb04fNrni3d/WFwpEifha89ir9UEH6prhknjbZRP5U/CUwLYPGcUBMLaT2LtrdggPladippymHWFT3ykOdGoaWCVOSfiPxV6khudJrBQdNfL/zE2/AyMBTAK2zwCA22/IJag40Pgs+qHltWngvcdRebuWrFUHqnwijAIpF1migHmNpNcdSZVZdDV6yzhKoXVSEw6wbUBBocpRqpDccgl/A=
    username: AgBpeH42Apjr2/h5G8pB1oF4xnwph7ZAftF5uPZuU6Gs84wRAxLov+Akw5zeW10O5qI33IFFTUf85EB8aPlEKfu89WDkBOm/xs2EIRmpWpW0T0trDjuLUnekya2VnH5EryyYu+XM2y+DsaOKVDRMbcRzzPvX/M2ZQUAaUTnXPfvPn1InW654sOMxTTCVfo8o+bz5j/nHIXAdPr0s2AalmrVrBdfmmqnvIhs8fgJIWQFA9YNPiDInR199Y6PPG8ib3thX5H/uceRdeSxiDZzbo5g/63Xc5p8XzLVdhwRAa1nkVSfx8RrwGZD5fl5FNrCarN2ICo+bGuCINiNVjsmqJM0bny4KjojD2qQW2aeLspPJJCNKaeGXEN5Hi0cASRf+A/vq75cj6kIFt3W4+xo8yMFeMoNtR8yCJjllZ/37497lujfqLQ9fbglACYJ3mzT1gd93DqbOGVLWRuFziCxiNrxZDcCbk0vvy2AqyOWGrUQAyevhziMNsAshMpO05eqPTbC6Putpe+aZDfAVgsORfZJdMertoxdcoY1EkUXl6ZW0EUqYh/jyq1xfBQJBN6RDs/l6zCWAoogGgOYfcIhQkwYHSrjiCvkJJjjIyK1YHVTLxP6Lp91H5OjJWcFNtrrxaumlUg2mguSFn6YS+emICLHALtyPXs1gvWRypy3RgLiViVgYBIGMR7jIULYLrc5K37rF1mM/IyPF5TJQ8f8=
  template:
    metadata:
      creationTimestamp: null
      name: git-creds
      namespace: argocd
